Enable FFN fusion
intel/intel-extension-for-transformers pull request #160
Opened 2023-08-23 01:57 UTC by intellinjun

## Type of Change

Add FFN fusion for gptneox-20b，Dolly-v2-3B, Mpt-7B, Starcode-3B, falcon-7B

2023-08-23 01:59 UTC, airMeng commented on intel_extension_for_transformers/backends/neural_engine/graph/models/gptneox/gptneox.cpp
> +#define FFN_FUSION 1
format

2023-08-23 02:06 UTC, intellinjun commented
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/52/

2023-09-03 09:06 UTC, airMeng commented
please update with latest API https://github.com/intel/intel-extension-for-transformers/blob/793629f11a775a05b5c22ee53224020516926eac/intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp#L204

2023-09-05 07:19 UTC, a32543254 approved these changes
LGTM

2023-09-06 05:04 UTC, intellinjun commented
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/71/

2023-09-07 05:36 UTC, luoyu-intel requested changes
remove repeat op.

2023-09-07 05:36 UTC, luoyu-intel commented on intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
>    cur = ne_add(ctx0, ne_mul(ctx0, ne_repeat(ctx0, layer.norm[2], cur), cur), ne_repeat(ctx0, layer.norm[3], cur));
@yuchengliu1 has implemented non-repeat add, please update with him.

2023-09-07 05:39 UTC, kevinintel approved these changes
LGTM

2023-09-07 05:42 UTC, luoyu-intel commented on intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
>    cur = ne_add(ctx0, ne_mul(ctx0, ne_repeat(ctx0, layer.norm[2], cur), cur), ne_repeat(ctx0, layer.norm[3], cur));
move to the next pr.

2023-09-07 05:42 UTC, luoyu-intel approved these changes

2023-09-07 05:45 UTC, airMeng commented
> https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/71/

failed?

2023-09-07 05:50 UTC, intellinjun commented
> > https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/ITREX-cpp-graph-extension/71/
> 
> failed?

failed Since yesterday a pr in zhentao modified the command line of inference, causing inference to fail, I retested it, still in queue, I tested it locally and there is no problem

2023-09-07 07:02 UTC, merged

2023-09-11 02:25 UTC, Zhenzhong1 commented on intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp
> +        if (jblas_fusion_FFN_Add_GeLu_f32f32_support(model.layers[il].ffn[0]->data, model.layers[il].ffn[2]->data,
Please check input parameters of  jblas_fusion_FFN_Add_GeLu_f32f32_support for Bloom and GPTNeox. Their FFN[0] has different meanings.