Yuxiang/ut add
intel/intel-extension-for-transformers pull request #466
Opened 2023-10-13 08:17 UTC by Liangyx2

add ut `test_cut_video.py`

2023-10-16 15:20 UTC, DDEle requested changes

2023-10-16 22:58 UTC, airMeng commented
please avoid uploading huge binary files which is strongly not recommended

2023-10-17 15:59 UTC, DDEle requested changes
![image](https://github.com/intel/intel-extension-for-transformers/assets/28386673/a23ee606-ae60-4639-9319-3f7670c2409b)
I just cloned a new itrex and it was still there (in the history of this branch).

As I said, you have to **change your existing commits and force-push** (it's not undoing their changes with new commits) your changes to rewrite the git history.

If you don't know how change existing commits, an alternative can be that just delete this branch [here](https://github.com/intel/intel-extension-for-transformers/branches) and work on a new branch.

2023-10-17 16:12 UTC, DDEle approved these changes
![image](https://github.com/intel/intel-extension-for-transformers/assets/28386673/a23ee606-ae60-4639-9319-3f7670c2409b)
I just cloned a new itrex and it was still there (in the history of this branch).

As I said, you have to change your existing commits and force-push (it's not undoing their changes with new commits) your changes to rewrite the git history.

Anyway, as our PR is merged by squashing, we should automatically get rid of `intel.mp4` after the merging of this PR (and deleting the branch `yuxiang/ut_add`).

2023-10-19 05:48 UTC, lvliang-intel approved these changes

2023-10-20 05:47 UTC, merged